### ISSUE TITLE
feat: rearrange evolution cards to the front in card input display

### ISSUE THREAD

**Issue by NipulM** [NipulM/cr-api-python-clientjs#2]
When a user inputs a correct card name, the current behaviour does not prioritise the display of evolution cards.

![Screenshot 2024-02-09 at 20 45 11](https://github.com/NipulM/cr-api-python-clientjs/assets/125451160/9c1ca30e-fdc0-4a5b-83f1-b29273dbb74c)

**Comment by randilt** [comment]
I'll take a look into this
